class AddError(Exception):
    pass

class CreationError(Exception):
    pass